language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - master
    - develop
    - feature#00
    
notifications:
  email:
    recipients:
      - davidchiva3@gmail.com
      
script: mvn verify